################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/croutine.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/event_groups.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_1.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_2.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_3.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_4.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_5.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/list.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/queue.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/tasks.c \
C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/timers.c 

OBJS += \
./FreeRTOS/src/croutine.o \
./FreeRTOS/src/event_groups.o \
./FreeRTOS/src/heap_1.o \
./FreeRTOS/src/heap_2.o \
./FreeRTOS/src/heap_3.o \
./FreeRTOS/src/heap_4.o \
./FreeRTOS/src/heap_5.o \
./FreeRTOS/src/list.o \
./FreeRTOS/src/queue.o \
./FreeRTOS/src/tasks.o \
./FreeRTOS/src/timers.o 

C_DEPS += \
./FreeRTOS/src/croutine.d \
./FreeRTOS/src/event_groups.d \
./FreeRTOS/src/heap_1.d \
./FreeRTOS/src/heap_2.d \
./FreeRTOS/src/heap_3.d \
./FreeRTOS/src/heap_4.d \
./FreeRTOS/src/heap_5.d \
./FreeRTOS/src/list.d \
./FreeRTOS/src/queue.d \
./FreeRTOS/src/tasks.d \
./FreeRTOS/src/timers.d 


# Each subdirectory must supply rules for building sources it contributes
FreeRTOS/src/croutine.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/croutine.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/event_groups.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/event_groups.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/heap_1.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_1.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/heap_2.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_2.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/heap_3.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_3.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/heap_4.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_4.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/heap_5.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/heap_5.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/list.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/list.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/queue.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/tasks.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/tasks.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FreeRTOS/src/timers.o: C:/Freescale/KSDK_1.3.0/rtos/FreeRTOS/src/timers.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wall  -g3 -D"CPU_MKL25Z128VLK4" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\include" -I"C:\Users\thiag\Dropbox\IC\KL25Z\lib" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\port\gcc" -I"C:\Freescale\KSDK_1.3.0\rtos\FreeRTOS\config\KL25Z4\gcc" -I"../Sources" -I"../Project_Settings/Startup_Code" -I"../SDK/platform/CMSIS/Include" -I"../SDK/platform/devices" -I"../SDK/platform/devices/MKL25Z4/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/src" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/include" -I"C:\Freescale\KSDK_1.3.0/rtos/FreeRTOS/port/gcc" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/string" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/config/common" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/include" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/kernel" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/bsp" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_serial/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/strings" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy/src" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/cpu" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/core/M0" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/fs" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx_stdlib/source/stdio" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_tty" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/psp/cortex_m/compiler/gcc_arm" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/nio/drivers/nio_dummy" -I"C:\Freescale\KSDK_1.3.0/rtos/mqx/mqx/source/include" -std=c99 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


